language: python

before_install:
  - pip install flake8 flake8-docstrings

jobs:
  include:
    - name: Lint client
      script: flake8 client
    - name: Lint server
      script: flake8 server --exclude server/migrations
    - name: Test server
      before_install: pip install pytest pytest-cov
      install: pip install ./server
      script: pytest --cov=./server/hotdesk ./server
