language: python

install:
  - pip install flake8 flake8-docstrings

script:
  - flake8

jobs:
  include:
    - name: Lint client
      script: flake8 client
    - name: Lint server
      script: flake8 server --exclude server/migrations
