"""Initial Migration

Revision ID: 8b8d770c2e0a
Revises: 
Create Date: 2020-04-24 12:34:43.646173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8d770c2e0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('desks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('from_when', sa.DateTime(), nullable=True),
    sa.Column('until_when', sa.DateTime(), nullable=True),
    sa.Column('desk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['desk_id'], ['desks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('desks')
    # ### end Alembic commands ###
